/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2026-09-27 08:32:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/includes/footer.jsp", Long.valueOf(1790497547421L));
    _jspx_dependants.put("/includes/header.jsp", Long.valueOf(1790445127966L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

    String adminUsername = (session != null) ? (String) session.getAttribute("adminUsername") : null;
    String cp = request.getContextPath();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>LifeDrop - Blood Donor Management System</title>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"");
      out.print( cp );
      out.write("/assets/css/style.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg app-navbar sticky-top\" style=\"z-index:1000;\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <a class=\"navbar-brand d-flex align-items-center gap-2\" href=\"");
      out.print( cp );
      out.write("/index.jsp\">\n");
      out.write("            <div style=\"width:36px;height:36px;background:linear-gradient(135deg,#dc2626,#b91c1c);border-radius:10px;display:flex;align-items:center;justify-content:center;box-shadow:0 3px 10px rgba(220,38,38,0.35);\">\n");
      out.write("                <i class=\"fa-solid fa-droplet text-white\" style=\"font-size:0.9rem;\"></i>\n");
      out.write("            </div>\n");
      out.write("            <span style=\"color:#1e3a5f;font-weight:800;letter-spacing:-0.5px;\">Life<span style=\"color:#dc2626;\">Drop</span></span>\n");
      out.write("        </a>\n");
      out.write("        <button class=\"navbar-toggler border-0\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navMenu\">\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("        </button>\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navMenu\">\n");
      out.write("            <ul class=\"navbar-nav mx-auto align-items-center gap-1\">\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print( cp );
      out.write("/index.jsp\"><i class=\"fa-solid fa-house me-1 text-red\"></i>Home</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print( cp );
      out.write("/registerDonor\"><i class=\"fa-solid fa-user-plus me-1 text-red\"></i>Register</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print( cp );
      out.write("/searchDonors\"><i class=\"fa-solid fa-magnifying-glass me-1 text-red\"></i>Search</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print( cp );
      out.write("/contact.jsp\"><i class=\"fa-solid fa-envelope me-1 text-red\"></i>Contact</a></li>\n");
      out.write("                ");
 if (adminUsername != null) { 
      out.write("\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print( cp );
      out.write("/adminDashboard\"><i class=\"fa-solid fa-gauge me-1 text-red\"></i>Dashboard</a></li>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </ul>\n");
      out.write("            <div class=\"d-flex align-items-center gap-2 ms-2\">\n");
      out.write("                ");
 if (adminUsername != null) { 
      out.write("\n");
      out.write("                    <span class=\"text-muted small me-1\"><i class=\"fa-solid fa-circle-user me-1\"></i>");
      out.print( adminUsername );
      out.write("</span>\n");
      out.write("                    <a href=\"");
      out.print( cp );
      out.write("/adminLogout\" class=\"btn-admin-nav nav-link\">\n");
      out.write("                        <i class=\"fa-solid fa-right-from-bracket me-1\"></i>Logout\n");
      out.write("                    </a>\n");
      out.write("                ");
 } else { 
      out.write("\n");
      out.write("                    <a href=\"");
      out.print( cp );
      out.write("/adminLogin\" class=\"btn-admin-nav nav-link\">\n");
      out.write("                        <i class=\"fa-solid fa-user-shield me-1\"></i>Admin Login\n");
      out.write("                    </a>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<main class=\"app-main\">\r\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- HERO -->\n");
      out.write("<section style=\"background:linear-gradient(135deg,#1e3a5f 0%,#dc2626 100%);min-height:88vh;display:flex;align-items:center;padding:4rem 0;position:relative;overflow:hidden;\">\n");
      out.write("    <div style=\"position:absolute;top:-100px;right:-100px;width:500px;height:500px;background:rgba(255,255,255,0.03);border-radius:50%;\"></div>\n");
      out.write("    <div style=\"position:absolute;bottom:-150px;left:-100px;width:600px;height:600px;background:rgba(255,255,255,0.03);border-radius:50%;\"></div>\n");
      out.write("    <div class=\"container\" style=\"position:relative;z-index:1;\">\n");
      out.write("        <div class=\"row align-items-center g-5\">\n");
      out.write("            <div class=\"col-lg-6\">\n");
      out.write("                <div style=\"display:inline-flex;align-items:center;gap:8px;background:rgba(255,255,255,0.12);border:1px solid rgba(255,255,255,0.2);color:#fff;padding:0.4rem 1rem;border-radius:50px;font-size:0.82rem;font-weight:500;margin-bottom:1.5rem;\">\n");
      out.write("                    <i class=\"fa-solid fa-heart-pulse\"></i> India Needs 5 Crore Units Annually — Be a Hero\n");
      out.write("                </div>\n");
      out.write("                <h1 style=\"font-size:clamp(2.2rem,5vw,3.6rem);font-weight:800;color:#fff;line-height:1.15;letter-spacing:-1px;margin-bottom:1.2rem;\">\n");
      out.write("                    Donate Blood,<br>\n");
      out.write("                    <span style=\"background:linear-gradient(90deg,#fbbf24,#f59e0b);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;\">Save Lives</span><br>\n");
      out.write("                    Be a Hero\n");
      out.write("                </h1>\n");
      out.write("                <p style=\"font-size:1.05rem;color:rgba(255,255,255,0.8);line-height:1.75;margin-bottom:2rem;max-width:500px;\">\n");
      out.write("                    LifeDrop connects blood donors with people who need them. Register in minutes, search by blood group and city, and help save a life today.\n");
      out.write("                </p>\n");
      out.write("                <div class=\"d-flex flex-wrap gap-3\">\n");
      out.write("                    <a href=\"");
      out.print( cp );
      out.write("/registerDonor\" class=\"btn-primary-custom\">\n");
      out.write("                        <i class=\"fa-solid fa-hand-holding-heart\"></i> Become a Donor\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"");
      out.print( cp );
      out.write("/searchDonors\" class=\"btn-secondary-custom\">\n");
      out.write("                        <i class=\"fa-solid fa-magnifying-glass\"></i> Find a Donor\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"d-flex gap-4 mt-4\">\n");
      out.write("                    <div style=\"color:rgba(255,255,255,0.7);font-size:0.85rem;\"><i class=\"fa-solid fa-shield-check me-1\" style=\"color:#4ade80;\"></i>Free to Register</div>\n");
      out.write("                    <div style=\"color:rgba(255,255,255,0.7);font-size:0.85rem;\"><i class=\"fa-solid fa-lock me-1\" style=\"color:#4ade80;\"></i>Data Secure</div>\n");
      out.write("                    <div style=\"color:rgba(255,255,255,0.7);font-size:0.85rem;\"><i class=\"fa-solid fa-clock me-1\" style=\"color:#4ade80;\"></i>24/7 Access</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-6\">\n");
      out.write("                <div class=\"row g-3\">\n");
      out.write("                    <div class=\"col-6\"><div class=\"stat-mini\"><i class=\"fa-solid fa-users fa-2x\"></i><h3>500+</h3><small>Registered Donors</small></div></div>\n");
      out.write("                    <div class=\"col-6\"><div class=\"stat-mini\"><i class=\"fa-solid fa-droplet fa-2x\"></i><h3>8</h3><small>Blood Types Covered</small></div></div>\n");
      out.write("                    <div class=\"col-6\"><div class=\"stat-mini\"><i class=\"fa-solid fa-heart fa-2x\"></i><h3>1000+</h3><small>Lives Saved</small></div></div>\n");
      out.write("                    <div class=\"col-6\"><div class=\"stat-mini\"><i class=\"fa-solid fa-hospital fa-2x\"></i><h3>50+</h3><small>Partner Hospitals</small></div></div>\n");
      out.write("                </div>\n");
      out.write("                <div style=\"background:#fff;border-radius:16px;padding:1.25rem;margin-top:1rem;box-shadow:0 20px 60px rgba(0,0,0,0.25);display:flex;align-items:center;gap:1rem;\">\n");
      out.write("                    <div style=\"background:#fef2f2;border-radius:12px;padding:0.85rem;flex-shrink:0;\">\n");
      out.write("                        <i class=\"fa-solid fa-droplet fa-2x\" style=\"color:#dc2626;\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <div style=\"flex:1;\">\n");
      out.write("                        <div style=\"font-weight:700;font-size:0.9rem;color:#1f2937;\">Emergency Blood Request</div>\n");
      out.write("                        <div style=\"color:#6b7280;font-size:0.8rem;margin-top:2px;\">Find donors in your city instantly</div>\n");
      out.write("                    </div>\n");
      out.write("                    <a href=\"");
      out.print( cp );
      out.write("/searchDonors\" class=\"btn-red\" style=\"flex-shrink:0;font-size:0.82rem;padding:0.5rem 1rem;\">\n");
      out.write("                        Search <i class=\"fa-solid fa-arrow-right ms-1\"></i>\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- QUICK SEARCH -->\n");
      out.write("<section class=\"container\" style=\"margin-top:-30px;position:relative;z-index:10;\">\n");
      out.write("    <div class=\"card-custom p-4\" style=\"box-shadow:0 8px 40px rgba(0,0,0,0.12);\">\n");
      out.write("        <div class=\"d-flex align-items-center gap-2 mb-3\">\n");
      out.write("            <i class=\"fa-solid fa-bolt\" style=\"color:#f59e0b;\"></i>\n");
      out.write("            <h5 class=\"mb-0 fw-700\">Quick Donor Search</h5>\n");
      out.write("            <span class=\"ms-2\" style=\"background:#fef2f2;color:#dc2626;font-size:0.72rem;font-weight:700;padding:0.2rem 0.6rem;border-radius:20px;\">LIVE</span>\n");
      out.write("        </div>\n");
      out.write("        <form action=\"");
      out.print( cp );
      out.write("/searchDonors\" method=\"get\">\n");
      out.write("            <div class=\"row g-3 align-items-end\">\n");
      out.write("                <div class=\"col-md-4\">\n");
      out.write("                    <label class=\"form-label\">Blood Group Needed</label>\n");
      out.write("                    <select name=\"bloodGroup\" class=\"form-select\">\n");
      out.write("                        <option value=\"\">Any Blood Group</option>\n");
      out.write("                        ");
 for (String g : new String[]{"A+","A-","B+","B-","AB+","AB-","O+","O-"}) { 
      out.write("\n");
      out.write("                            <option value=\"");
      out.print( g );
      out.write('"');
      out.write('>');
      out.print( g );
      out.write("</option>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                    </select>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-5\">\n");
      out.write("                    <label class=\"form-label\">City</label>\n");
      out.write("                    <div class=\"input-group\">\n");
      out.write("                        <span class=\"input-group-text\"><i class=\"fa-solid fa-location-dot\"></i></span>\n");
      out.write("                        <input type=\"text\" name=\"city\" class=\"form-control\" style=\"border-radius:0 10px 10px 0;\" placeholder=\"e.g. Mumbai, Delhi, Pune...\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-3\">\n");
      out.write("                    <button type=\"submit\" class=\"btn-red w-100\" style=\"justify-content:center;padding:0.68rem;\">\n");
      out.write("                        <i class=\"fa-solid fa-magnifying-glass\"></i> Search Now\n");
      out.write("                    </button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- BLOOD GROUP QUICK LINKS -->\n");
      out.write("<section class=\"container py-5\">\n");
      out.write("    <div class=\"text-center mb-4\">\n");
      out.write("        <span class=\"section-label\">Browse by Blood Type</span>\n");
      out.write("        <h2 class=\"section-heading mt-2\">Find Donors by Blood Group</h2>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"row g-3 justify-content-center\">\n");
      out.write("        ");
 String[] bgroups = {"A+","A-","B+","B-","AB+","AB-","O+","O-"};
           String[] colors = {"#dc2626","#b91c1c","#dc2626","#b91c1c","#dc2626","#b91c1c","#dc2626","#b91c1c"};
           for (int i=0; i<bgroups.length; i++) { 
      out.write("\n");
      out.write("        <div class=\"col-6 col-sm-3 col-md-3 col-lg-auto\">\n");
      out.write("            <a href=\"");
      out.print( cp );
      out.write("/searchDonors?bloodGroup=");
      out.print( bgroups[i] );
      out.write("\" class=\"card-custom d-block text-center p-3 text-decoration-none\" style=\"min-width:110px;\">\n");
      out.write("                <div style=\"font-size:2rem;font-weight:800;color:");
      out.print( colors[i] );
      out.write(";line-height:1.2;\">");
      out.print( bgroups[i] );
      out.write("</div>\n");
      out.write("                <div style=\"font-size:0.75rem;color:#6b7280;margin-top:4px;\">Find Donors</div>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- HOW IT WORKS -->\n");
      out.write("<section style=\"background:#f3f4f6;padding:5rem 0;\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"text-center mb-5\">\n");
      out.write("            <span class=\"section-label\">Simple Process</span>\n");
      out.write("            <h2 class=\"section-heading mt-2\">How LifeDrop Works</h2>\n");
      out.write("            <p class=\"text-muted mt-2\">Three easy steps that can save a life</p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"row g-4\">\n");
      out.write("            <div class=\"col-md-4\">\n");
      out.write("                <div class=\"card-custom p-4 h-100 position-relative\" style=\"overflow:hidden;\">\n");
      out.write("                    <div style=\"position:absolute;top:1rem;right:1.5rem;font-size:3rem;font-weight:800;color:#f3f4f6;line-height:1;z-index:0;\">01</div>\n");
      out.write("                    <div style=\"position:relative;z-index:1;\">\n");
      out.write("                        <div class=\"feature-icon-box mb-3\"><i class=\"fa-solid fa-user-plus\"></i></div>\n");
      out.write("                        <h5 class=\"fw-700 mb-2\">Register as Donor</h5>\n");
      out.write("                        <p class=\"text-muted mb-3\" style=\"font-size:0.88rem;line-height:1.65;\">Fill in your name, blood group, phone, email, address and city. Registration takes under 2 minutes.</p>\n");
      out.write("                        <a href=\"");
      out.print( cp );
      out.write("/registerDonor\" class=\"btn-red\" style=\"font-size:0.82rem;padding:0.5rem 1.1rem;\">Register Now <i class=\"fa-solid fa-arrow-right ms-1\"></i></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-4\">\n");
      out.write("                <div class=\"card-custom p-4 h-100 position-relative\" style=\"overflow:hidden;border-color:rgba(220,38,38,0.2);\">\n");
      out.write("                    <div style=\"position:absolute;top:1rem;right:1.5rem;font-size:3rem;font-weight:800;color:#fef2f2;line-height:1;z-index:0;\">02</div>\n");
      out.write("                    <div style=\"position:relative;z-index:1;\">\n");
      out.write("                        <div class=\"feature-icon-box mb-3\"><i class=\"fa-solid fa-magnifying-glass\"></i></div>\n");
      out.write("                        <h5 class=\"fw-700 mb-2\">Search Donors</h5>\n");
      out.write("                        <p class=\"text-muted mb-3\" style=\"font-size:0.88rem;line-height:1.65;\">Filter donors by blood group and city. See name, age, gender, city and last donation date instantly.</p>\n");
      out.write("                        <a href=\"");
      out.print( cp );
      out.write("/searchDonors\" class=\"btn-red\" style=\"font-size:0.82rem;padding:0.5rem 1.1rem;\">Search Now <i class=\"fa-solid fa-arrow-right ms-1\"></i></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-4\">\n");
      out.write("                <div class=\"card-custom p-4 h-100 position-relative\" style=\"overflow:hidden;\">\n");
      out.write("                    <div style=\"position:absolute;top:1rem;right:1.5rem;font-size:3rem;font-weight:800;color:#f3f4f6;line-height:1;z-index:0;\">03</div>\n");
      out.write("                    <div style=\"position:relative;z-index:1;\">\n");
      out.write("                        <div class=\"feature-icon-box mb-3\"><i class=\"fa-solid fa-phone\"></i></div>\n");
      out.write("                        <h5 class=\"fw-700 mb-2\">Connect & Donate</h5>\n");
      out.write("                        <p class=\"text-muted mb-3\" style=\"font-size:0.88rem;line-height:1.65;\">Contact the donor or reach out through our platform. Coordinate and complete the life-saving donation.</p>\n");
      out.write("                        <a href=\"");
      out.print( cp );
      out.write("/contact.jsp\" class=\"btn-red\" style=\"font-size:0.82rem;padding:0.5rem 1.1rem;\">Contact Us <i class=\"fa-solid fa-arrow-right ms-1\"></i></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- WHY DONATE -->\n");
      out.write("<section style=\"padding:5rem 0;background:#fff;\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row align-items-center g-5\">\n");
      out.write("            <div class=\"col-lg-6\">\n");
      out.write("                <span class=\"section-label\">Why Donate?</span>\n");
      out.write("                <h2 class=\"section-heading mt-2 mb-4\">Your Blood Can Save<br>Up to 3 Lives</h2>\n");
      out.write("                <div class=\"d-flex flex-column gap-3\">\n");
      out.write("                    <div class=\"d-flex gap-3 align-items-start p-3 rounded-3\" style=\"background:#fef2f2;\">\n");
      out.write("                        <div style=\"width:36px;height:36px;background:#dc2626;border-radius:8px;display:flex;align-items:center;justify-content:center;flex-shrink:0;\">\n");
      out.write("                            <i class=\"fa-solid fa-check text-white\" style=\"font-size:0.8rem;\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <div>\n");
      out.write("                            <div class=\"fw-600\" style=\"font-size:0.92rem;\">One donation can save up to 3 lives</div>\n");
      out.write("                            <div class=\"text-muted\" style=\"font-size:0.82rem;margin-top:2px;\">A single donation is separated into red cells, plasma and platelets</div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"d-flex gap-3 align-items-start p-3 rounded-3\" style=\"background:#f0fdf4;\">\n");
      out.write("                        <div style=\"width:36px;height:36px;background:#16a34a;border-radius:8px;display:flex;align-items:center;justify-content:center;flex-shrink:0;\">\n");
      out.write("                            <i class=\"fa-solid fa-check text-white\" style=\"font-size:0.8rem;\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <div>\n");
      out.write("                            <div class=\"fw-600\" style=\"font-size:0.92rem;\">Blood cannot be manufactured</div>\n");
      out.write("                            <div class=\"text-muted\" style=\"font-size:0.82rem;margin-top:2px;\">Only human donors can provide this life-saving resource</div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"d-flex gap-3 align-items-start p-3 rounded-3\" style=\"background:#eff6ff;\">\n");
      out.write("                        <div style=\"width:36px;height:36px;background:#2563eb;border-radius:8px;display:flex;align-items:center;justify-content:center;flex-shrink:0;\">\n");
      out.write("                            <i class=\"fa-solid fa-check text-white\" style=\"font-size:0.8rem;\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <div>\n");
      out.write("                            <div class=\"fw-600\" style=\"font-size:0.92rem;\">Someone needs blood every 2 seconds</div>\n");
      out.write("                            <div class=\"text-muted\" style=\"font-size:0.82rem;margin-top:2px;\">India collects only 2.5 crore units vs the 5 crore needed annually</div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"d-flex gap-3 align-items-start p-3 rounded-3\" style=\"background:#fefce8;\">\n");
      out.write("                        <div style=\"width:36px;height:36px;background:#d97706;border-radius:8px;display:flex;align-items:center;justify-content:center;flex-shrink:0;\">\n");
      out.write("                            <i class=\"fa-solid fa-check text-white\" style=\"font-size:0.8rem;\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <div>\n");
      out.write("                            <div class=\"fw-600\" style=\"font-size:0.92rem;\">Donating blood is safe and healthy</div>\n");
      out.write("                            <div class=\"text-muted\" style=\"font-size:0.82rem;margin-top:2px;\">Your body replenishes donated blood within 24-48 hours</div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-6\">\n");
      out.write("                <div style=\"background:linear-gradient(135deg,#1e3a5f,#2d5986);border-radius:24px;padding:2.5rem;color:#fff;\">\n");
      out.write("                    <h4 class=\"fw-700 mb-4 text-white text-center\">Eligibility Criteria</h4>\n");
      out.write("                    <div class=\"d-flex flex-column gap-3\">\n");
      out.write("                        <div class=\"d-flex align-items-center gap-3\">\n");
      out.write("                            <i class=\"fa-solid fa-person-circle-check fa-lg\" style=\"color:#4ade80;width:24px;\"></i>\n");
      out.write("                            <span style=\"font-size:0.9rem;\">Age between <strong>18 and 65 years</strong></span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"d-flex align-items-center gap-3\">\n");
      out.write("                            <i class=\"fa-solid fa-weight-scale fa-lg\" style=\"color:#4ade80;width:24px;\"></i>\n");
      out.write("                            <span style=\"font-size:0.9rem;\">Weight at least <strong>50 kg</strong></span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"d-flex align-items-center gap-3\">\n");
      out.write("                            <i class=\"fa-solid fa-temperature-low fa-lg\" style=\"color:#4ade80;width:24px;\"></i>\n");
      out.write("                            <span style=\"font-size:0.9rem;\">Normal body temperature <strong>(&lt;37.5°C)</strong></span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"d-flex align-items-center gap-3\">\n");
      out.write("                            <i class=\"fa-solid fa-calendar-check fa-lg\" style=\"color:#4ade80;width:24px;\"></i>\n");
      out.write("                            <span style=\"font-size:0.9rem;\">Gap of <strong>3 months</strong> between donations (men)</span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"d-flex align-items-center gap-3\">\n");
      out.write("                            <i class=\"fa-solid fa-calendar-check fa-lg\" style=\"color:#4ade80;width:24px;\"></i>\n");
      out.write("                            <span style=\"font-size:0.9rem;\">Gap of <strong>4 months</strong> between donations (women)</span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"d-flex align-items-center gap-3\">\n");
      out.write("                            <i class=\"fa-solid fa-virus-slash fa-lg\" style=\"color:#4ade80;width:24px;\"></i>\n");
      out.write("                            <span style=\"font-size:0.9rem;\">No major illness in the <strong>past 6 months</strong></span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <a href=\"");
      out.print( cp );
      out.write("/registerDonor\" class=\"btn-primary-custom w-100 mt-4\" style=\"justify-content:center;\">\n");
      out.write("                        <i class=\"fa-solid fa-heart-pulse\"></i> I'm Eligible — Register Now\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- BLOOD COMPATIBILITY TABLE -->\n");
      out.write("<section style=\"background:#f9fafb;padding:5rem 0;\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"text-center mb-4\">\n");
      out.write("            <span class=\"section-label\">Compatibility</span>\n");
      out.write("            <h2 class=\"section-heading mt-2\">Blood Type Compatibility Chart</h2>\n");
      out.write("            <p class=\"text-muted mt-2\">Know which blood types are compatible for donation and reception</p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"card-custom overflow-hidden\">\n");
      out.write("            <div class=\"table-responsive\">\n");
      out.write("                <table class=\"table mb-0 table-custom\">\n");
      out.write("                    <thead>\n");
      out.write("                        <tr>\n");
      out.write("                            <th>Blood Type</th>\n");
      out.write("                            <th>Can Donate To</th>\n");
      out.write("                            <th>Can Receive From</th>\n");
      out.write("                            <th>Special Note</th>\n");
      out.write("                        </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                        <tr>\n");
      out.write("                            <td><span class=\"blood-badge\">A+</span></td>\n");
      out.write("                            <td><span class=\"text-muted\" style=\"font-size:0.85rem;\">A+, AB+</span></td>\n");
      out.write("                            <td><span class=\"text-muted\" style=\"font-size:0.85rem;\">A+, A-, O+, O-</span></td>\n");
      out.write("                            <td><span style=\"font-size:0.8rem;\">Common type</span></td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td><span class=\"blood-badge\">A-</span></td>\n");
      out.write("                            <td><span class=\"text-muted\" style=\"font-size:0.85rem;\">A+, A-, AB+, AB-</span></td>\n");
      out.write("                            <td><span class=\"text-muted\" style=\"font-size:0.85rem;\">A-, O-</span></td>\n");
      out.write("                            <td><span style=\"font-size:0.8rem;\">Universal plasma donor</span></td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td><span class=\"blood-badge\">B+</span></td>\n");
      out.write("                            <td><span class=\"text-muted\" style=\"font-size:0.85rem;\">B+, AB+</span></td>\n");
      out.write("                            <td><span class=\"text-muted\" style=\"font-size:0.85rem;\">B+, B-, O+, O-</span></td>\n");
      out.write("                            <td><span style=\"font-size:0.8rem;\">Common in South Asia</span></td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td><span class=\"blood-badge\">B-</span></td>\n");
      out.write("                            <td><span class=\"text-muted\" style=\"font-size:0.85rem;\">B+, B-, AB+, AB-</span></td>\n");
      out.write("                            <td><span class=\"text-muted\" style=\"font-size:0.85rem;\">B-, O-</span></td>\n");
      out.write("                            <td><span style=\"font-size:0.8rem;\">Rare — donate often</span></td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td><span class=\"blood-badge\">AB+</span></td>\n");
      out.write("                            <td><span class=\"text-muted\" style=\"font-size:0.85rem;\">AB+ only</span></td>\n");
      out.write("                            <td><span class=\"text-muted\" style=\"font-size:0.85rem;\">All blood types</span></td>\n");
      out.write("                            <td><span style=\"background:#d1fae5;color:#065f46;padding:0.2rem 0.5rem;border-radius:6px;font-size:0.75rem;font-weight:600;\">Universal Recipient</span></td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td><span class=\"blood-badge\">AB-</span></td>\n");
      out.write("                            <td><span class=\"text-muted\" style=\"font-size:0.85rem;\">AB+, AB-</span></td>\n");
      out.write("                            <td><span class=\"text-muted\" style=\"font-size:0.85rem;\">A-, B-, AB-, O-</span></td>\n");
      out.write("                            <td><span style=\"font-size:0.8rem;\">Rarest blood type</span></td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td><span class=\"blood-badge\">O+</span></td>\n");
      out.write("                            <td><span class=\"text-muted\" style=\"font-size:0.85rem;\">A+, B+, AB+, O+</span></td>\n");
      out.write("                            <td><span class=\"text-muted\" style=\"font-size:0.85rem;\">O+, O-</span></td>\n");
      out.write("                            <td><span style=\"background:#dbeafe;color:#1e40af;padding:0.2rem 0.5rem;border-radius:6px;font-size:0.75rem;font-weight:600;\">Most Common</span></td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td><span class=\"blood-badge\">O-</span></td>\n");
      out.write("                            <td><span class=\"text-muted\" style=\"font-size:0.85rem;\">All blood types</span></td>\n");
      out.write("                            <td><span class=\"text-muted\" style=\"font-size:0.85rem;\">O- only</span></td>\n");
      out.write("                            <td><span style=\"background:#fef2f2;color:#991b1b;padding:0.2rem 0.5rem;border-radius:6px;font-size:0.75rem;font-weight:600;\">Universal Donor</span></td>\n");
      out.write("                        </tr>\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- FAQ -->\n");
      out.write("<section style=\"padding:5rem 0;background:#fff;\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"text-center mb-5\">\n");
      out.write("            <span class=\"section-label\">FAQ</span>\n");
      out.write("            <h2 class=\"section-heading mt-2\">Common Questions</h2>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"row justify-content-center\">\n");
      out.write("            <div class=\"col-lg-8\">\n");
      out.write("                <div class=\"accordion\" id=\"faqAccordion\">\n");
      out.write("                    <div class=\"accordion-item border-0 mb-3 rounded-3 overflow-hidden\" style=\"box-shadow:0 2px 10px rgba(0,0,0,0.06);\">\n");
      out.write("                        <h2 class=\"accordion-header\">\n");
      out.write("                            <button class=\"accordion-button fw-600\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#faq1\" style=\"font-size:0.92rem;\">\n");
      out.write("                                How often can I donate blood?\n");
      out.write("                            </button>\n");
      out.write("                        </h2>\n");
      out.write("                        <div id=\"faq1\" class=\"accordion-collapse collapse show\" data-bs-parent=\"#faqAccordion\">\n");
      out.write("                            <div class=\"accordion-body text-muted\" style=\"font-size:0.88rem;\">Men can donate every 3 months (90 days) and women every 4 months (120 days). This gives your body enough time to replenish the donated blood.</div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"accordion-item border-0 mb-3 rounded-3 overflow-hidden\" style=\"box-shadow:0 2px 10px rgba(0,0,0,0.06);\">\n");
      out.write("                        <h2 class=\"accordion-header\">\n");
      out.write("                            <button class=\"accordion-button collapsed fw-600\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#faq2\" style=\"font-size:0.92rem;\">\n");
      out.write("                                Is blood donation safe?\n");
      out.write("                            </button>\n");
      out.write("                        </h2>\n");
      out.write("                        <div id=\"faq2\" class=\"accordion-collapse collapse\" data-bs-parent=\"#faqAccordion\">\n");
      out.write("                            <div class=\"accordion-body text-muted\" style=\"font-size:0.88rem;\">Yes, blood donation is completely safe. Sterile, single-use equipment is used for every donation. The process takes about 8-10 minutes and your body replenishes the donated blood within 24-48 hours.</div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"accordion-item border-0 mb-3 rounded-3 overflow-hidden\" style=\"box-shadow:0 2px 10px rgba(0,0,0,0.06);\">\n");
      out.write("                        <h2 class=\"accordion-header\">\n");
      out.write("                            <button class=\"accordion-button collapsed fw-600\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#faq3\" style=\"font-size:0.92rem;\">\n");
      out.write("                                What should I do before donating blood?\n");
      out.write("                            </button>\n");
      out.write("                        </h2>\n");
      out.write("                        <div id=\"faq3\" class=\"accordion-collapse collapse\" data-bs-parent=\"#faqAccordion\">\n");
      out.write("                            <div class=\"accordion-body text-muted\" style=\"font-size:0.88rem;\">Drink plenty of water, eat a healthy meal, avoid alcohol for 24 hours, and get a good night's sleep. Wear comfortable clothing with sleeves that can be rolled up easily.</div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"accordion-item border-0 rounded-3 overflow-hidden\" style=\"box-shadow:0 2px 10px rgba(0,0,0,0.06);\">\n");
      out.write("                        <h2 class=\"accordion-header\">\n");
      out.write("                            <button class=\"accordion-button collapsed fw-600\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#faq4\" style=\"font-size:0.92rem;\">\n");
      out.write("                                How is my data protected on LifeDrop?\n");
      out.write("                            </button>\n");
      out.write("                        </h2>\n");
      out.write("                        <div id=\"faq4\" class=\"accordion-collapse collapse\" data-bs-parent=\"#faqAccordion\">\n");
      out.write("                            <div class=\"accordion-body text-muted\" style=\"font-size:0.88rem;\">All admin passwords are hashed using BCrypt encryption. Your contact details are only visible to verified admins — the public search only shows your name, blood group, city and last donation date, never your phone or email directly.</div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- CTA BANNER -->\n");
      out.write("<section class=\"container pb-5\">\n");
      out.write("    <div style=\"background:linear-gradient(135deg,#dc2626,#b91c1c);border-radius:24px;padding:3.5rem 2rem;text-align:center;position:relative;overflow:hidden;\">\n");
      out.write("        <div style=\"position:absolute;top:-60px;right:-60px;width:220px;height:220px;background:rgba(255,255,255,0.05);border-radius:50%;\"></div>\n");
      out.write("        <div style=\"position:absolute;bottom:-80px;left:-60px;width:280px;height:280px;background:rgba(255,255,255,0.05);border-radius:50%;\"></div>\n");
      out.write("        <div style=\"position:relative;z-index:1;\">\n");
      out.write("            <i class=\"fa-solid fa-heart-circle-plus fa-3x text-white mb-3\" style=\"opacity:0.9;\"></i>\n");
      out.write("            <h2 class=\"text-white fw-800 mb-2\" style=\"font-size:clamp(1.5rem,3vw,2.2rem);\">Ready to Save a Life Today?</h2>\n");
      out.write("            <p style=\"color:rgba(255,255,255,0.85);font-size:1rem;max-width:500px;margin:0.5rem auto 2rem;\">Join our growing community of blood donors and make a difference. Registration is free, quick and secure.</p>\n");
      out.write("            <div class=\"d-flex justify-content-center gap-3 flex-wrap\">\n");
      out.write("                <a href=\"");
      out.print( cp );
      out.write("/registerDonor\" class=\"btn-primary-custom\">\n");
      out.write("                    <i class=\"fa-solid fa-user-plus\"></i> Register as Donor\n");
      out.write("                </a>\n");
      out.write("                <a href=\"");
      out.print( cp );
      out.write("/searchDonors\" class=\"btn-secondary-custom\">\n");
      out.write("                    <i class=\"fa-solid fa-search\"></i> Find Donors Now\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("</main>\n");
      out.write("\n");
      out.write("<footer class=\"app-footer\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row g-4 pb-4\" style=\"border-bottom:1px solid rgba(255,255,255,0.1);\">\n");
      out.write("            <div class=\"col-lg-4\">\n");
      out.write("                <div class=\"d-flex align-items-center gap-2 mb-3\">\n");
      out.write("                    <div style=\"width:36px;height:36px;background:linear-gradient(135deg,#dc2626,#b91c1c);border-radius:10px;display:flex;align-items:center;justify-content:center;\">\n");
      out.write("                        <i class=\"fa-solid fa-droplet text-white\" style=\"font-size:0.9rem;\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <span class=\"text-white fw-800\" style=\"font-size:1.1rem;\">Life<span style=\"color:#fca5a5;\">Drop</span></span>\n");
      out.write("                </div>\n");
      out.write("                <p style=\"font-size:0.85rem;line-height:1.7;max-width:280px;\">A Blood Donor Management System connecting donors with those in need. Built as a college mini-project.</p>\n");
      out.write("                <div class=\"d-flex gap-3 mt-3\">\n");
      out.write("                    <i class=\"fa-brands fa-github footer-link fa-lg\" style=\"cursor:pointer;\"></i>\n");
      out.write("  \n");
      out.write("             <i class=\"fa-solid fa-envelope footer-link fa-lg\" style=\"cursor:pointer;\"></i>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-2 col-6\">\n");
      out.write("                <h6 class=\"text-white fw-700 mb-3\">Navigation</h6>\n");
      out.write("                <div class=\"d-flex flex-column gap-2\">\n");
      out.write("                    <a href=\"index.jsp\" class=\"footer-link\">Home</a>\n");
      out.write("                    <a href=\"registerDonor\" class=\"footer-link\">Register</a>\n");
      out.write("                    <a href=\"searchDonors\" class=\"footer-link\">Search</a>\n");
      out.write("                    <a href=\"contact.jsp\" class=\"footer-link\">Contact</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-3 col-6\">\n");
      out.write("                <h6 class=\"text-white fw-700 mb-3\">Blood Groups</h6>\n");
      out.write("                <div class=\"d-flex flex-wrap gap-2\">\n");
      out.write("                    ");
 String[] bgs = {"A+","A-","B+","B-","AB+","AB-","O+","O-"};
                       for (String bg : bgs) { 
      out.write("\n");
      out.write("                        <a href=\"searchDonors?bloodGroup=");
      out.print( bg );
      out.write("\" class=\"blood-badge\" style=\"font-size:0.75rem;height:28px;min-width:40px;text-decoration:none;\">");
      out.print( bg );
      out.write("</a>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-3\">\n");
      out.write("                <h6 class=\"text-white fw-700 mb-3\">Emergency Contact</h6>\n");
      out.write("                <div class=\"d-flex flex-column gap-2\">\n");
      out.write("                    <div class=\"d-flex align-items-center gap-2\">\n");
      out.write("                        <i class=\"fa-solid fa-phone text-red\"></i>\n");
      out.write("                        <span style=\"font-size:0.85rem;\">+91 98765 43210</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"d-flex align-items-center gap-2\">\n");
      out.write("                        <i class=\"fa-solid fa-envelope text-red\"></i>\n");
      out.write("                        <span style=\"font-size:0.85rem;\">help@lifedrop.org</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"d-flex align-items-center gap-2\">\n");
      out.write("                        <i class=\"fa-solid fa-location-dot text-red\"></i>\n");
      out.write("                        <span style=\"font-size:0.85rem;\">Mumbai, Maharashtra</span>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"d-flex flex-wrap justify-content-between align-items-center pt-3 gap-2\">\n");
      out.write("            <p class=\"mb-0\" style=\"font-size:0.8rem;\">&copy; 2026 LifeDrop. Developed by <span class=\"text-white fw-600\">Nikhil Jain</span> | Java Servlets &middot; JSP &middot; JDBC &middot; MySQL</p>\n");
      out.write("            <p class=\"mb-0\" style=\"font-size:0.8rem;\">Made with <i class=\"fa-solid fa-heart text-red\"></i> for saving lives</p>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/assets/js/validation.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
